// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jynzkzucubcmhmidsgki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bnprenVjdWJjbWhtaWRzZ2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTQ3NzAsImV4cCI6MjA2MzU5MDc3MH0.D4De3B6dBeAzr86Ym41_Z317jWSMpVHu4feaj87CrDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);